/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_gl2jni_GL2JNIRender */

#ifndef _Included_com_android_gl2jni_GL2JNIRender
#define _Included_com_android_gl2jni_GL2JNIRender
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_android_gl2jni_GL2JNIRender
 * Method:    onDrawFrame
 * Signature: (Ljavax/microedition/khronos/opengles/GL10;)V
 */
JNIEXPORT void JNICALL Java_com_android_gl2jni_GL2JNIRender_onDrawFrame
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_android_gl2jni_GL2JNIRender
 * Method:    onSurfaceChanged
 * Signature: (Ljavax/microedition/khronos/opengles/GL10;II)V
 */
JNIEXPORT void JNICALL Java_com_android_gl2jni_GL2JNIRender_onSurfaceChanged
  (JNIEnv *, jobject, jobject, jint, jint);

/*
 * Class:     com_android_gl2jni_GL2JNIRender
 * Method:    onSurfaceCreated
 * Signature: (Ljavax/microedition/khronos/opengles/GL10;Ljavax/microedition/khronos/egl/EGLConfig;)V
 */
JNIEXPORT void JNICALL Java_com_android_gl2jni_GL2JNIRender_onSurfaceCreated
  (JNIEnv *, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
