/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_gl2jni_GL2JNIView */

#ifndef _Included_com_android_gl2jni_GL2JNIView
#define _Included_com_android_gl2jni_GL2JNIView
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_android_gl2jni_GL2JNIView
 * Method:    jsPause
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_android_gl2jni_GL2JNIView_jsPause
  (JNIEnv *, jclass);

/*
 * Class:     com_android_gl2jni_GL2JNIView
 * Method:    jsResume
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_android_gl2jni_GL2JNIView_jsResume
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
