/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_gl2jni_GL2JNIActivity */

#ifndef _Included_com_android_gl2jni_GL2JNIActivity
#define _Included_com_android_gl2jni_GL2JNIActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_android_gl2jni_GL2JNIActivity
 * Method:    initWithAsset
 * Signature: (Landroid/content/res/AssetManager;)V
 */
JNIEXPORT void JNICALL Java_com_android_gl2jni_GL2JNIActivity_initWithAsset
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_android_gl2jni_GL2JNIView
 * Method:    jsCreate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_android_gl2jni_GL2JNIActivity_jsCreate
  (JNIEnv *, jclass);

/*
 * Class:     com_android_gl2jni_GL2JNIView
 * Method:    jsDestory
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_android_gl2jni_GL2JNIActivity_jsDestory
  (JNIEnv *, jclass);

/*
 * Class:     com_android_gl2jni_GL2JNIActivity
 * Method:    evalScript
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_android_gl2jni_GL2JNIActivity_evalScript
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
